- name: Reset Nodes
  hosts: iosv_switches
  order: sorted
  gather_facts: no
  connection: local
  serial: 20  # Number of concurrent SSH sessions
  strategy: linear
  # Linear = wait for hosts, before running next task.
  # Free = each host runs each task as fast as it can.

  vars:
    provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"

  tasks:
    - block:
      - name: Configuration Replace
        ios_command:
          commands:
            - " configure replace nvram:startup-config force"
            - clear archive log config force
          timeout: 60
